[package]
name = "universal"
version = "0.1.0"
authors = ["Steven Barragán <me@steven.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
